# Backbone
<<<<<<< HEAD
backbone: resnet18
=======
backbone: resnet34
>>>>>>> 13980b57e7d4bdc14c29c0f6cc8533dd635e25e1

# Transfer loss related
transfer_loss_weight: 0.5
transfer_loss: lmmd

# Optimizer related
lr: 0.01
weight_decay: 5e-4
momentum: 0.9
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75

# Training related
n_iter_per_epoch: 500
n_epoch: 40

# Others
seed: 1
num_workers: 3
